# Generated by Django 3.0.3 on 2020-02-10 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prof', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wellnessprofessional',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
