# Generated by Django 3.0.3 on 2020-02-11 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prof', '0002_wellnessprofessional_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='wellnessprofessional',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pic/'),
        ),
    ]
