# Generated by Django 3.0.3 on 2020-02-18 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prof', '0003_wellnessprofessional_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wellnessprofessional',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='prof/profile_pic/'),
        ),
    ]
