# Generated by Django 3.0.3 on 2020-03-18 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prof', '0004_auto_20200218_0643'),
    ]

    operations = [
        migrations.AddField(
            model_name='wellnessprofessional',
            name='location_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='wellnessprofessional',
            name='location_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
