# Generated by Django 3.0.3 on 2020-05-12 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prof', '0005_auto_20200318_0652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wellnessprofessional',
            name='credentials',
        ),
        migrations.RemoveField(
            model_name='wellnessprofessional',
            name='specialties',
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialty', models.CharField(max_length=255)),
                ('wellness_professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prof.WellnessProfessional')),
            ],
            options={
                'db_table': '"specialty"',
            },
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_name', models.CharField(max_length=255)),
                ('license_number', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=2)),
                ('year', models.CharField(max_length=4)),
                ('wellness_professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prof.WellnessProfessional')),
            ],
            options={
                'db_table': '"license"',
            },
        ),
        migrations.CreateModel(
            name='EducationCredential',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=255)),
                ('degree', models.CharField(max_length=10)),
                ('major', models.CharField(max_length=255)),
                ('year_graduated', models.CharField(max_length=4)),
                ('wellness_professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prof.WellnessProfessional')),
            ],
            options={
                'db_table': '"education_credential"',
            },
        ),
    ]
