# Generated by Django 3.0.3 on 2020-05-21 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prof', '0006_auto_20200512_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='wellnessprofessional',
            name='profession',
            field=models.CharField(default='test', max_length=255),
            preserve_default=False,
        ),
    ]
