# Generated by Django 3.0.3 on 2020-02-08 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_create_wellnessprof_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wellnessprofessionals',
            name='address_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='wellnessprofessionals',
            name='credentials',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='wellnessprofessionals',
            name='specialties',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='wellnessprofessionals',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
